### ISSUE TITLE
Typo at `ORDER BY` Clause documentation.

### ISSUE THREAD

**Issue by diogo-gsa** [feedzai/pdb#43]
There is a typo regarding how PDB's `ORDER BY` Clause should be used together with the `ASC` argument. Currently, the documentation exemplifies the usage of both with the following expression: `orderby(column("data_type_id")).asc())`. However, such expression is not correct and thus it should be fixed to: `orderby(column("data_type_id").asc())`.

This issues is solved within the Pull Request: https://github.com/feedzai/pdb/pull/42

**Comment by jmf-tls** [comment]
As mentioned in the previous comment, this was fixed in #42
