### ISSUE TITLE
Documentation for the DatabaseEngine.commit() method is inconsistent

### ISSUE THREAD

**Issue by Pitxyoki** [feedzai/pdb#5]
The `DatabaseEngine.commit()` method states that it _throws DatabaseEngineException if something goes wrong while persisting data._
However, the method's declaration states that it can throw a `DatabaseEngine*Runtime*Exception`.

This is especially dangerous, as users of the API are intuitively taken to use a block such as:

``` java
boolean success = false;
while (!success) {
 try {
   //do something
   (...)

   engine.commit();
   success = true;
 } catch (DatabaseEngineException) {
   //deal with the error
 }
}
```

However, if a `DatabaseEngineRuntimeException` is thrown, it will never be caught by the catch block, and it will inevitably bubble up from the caller.

The javadoc should declare that a `DatabaseEngineRuntimeException` is thrown, or, better yet, the method should throw `DatabaseEngineException` to force the caller to deal with the exception (although that would now break the API).

**Comment by HiuKwok** [comment]
This already addressed by dc43aab6d757f8427b2181b78625230e468a323c .
