### ISSUE TITLE
Upgrade to Apache commons-lang3 instead of commons-lang

### ISSUE THREAD

**Issue by casewalker** [feedzai/pdb#51]
Apache commons-lang3 was designed to be able to live side-by-side with commons-lang, but it is extra bloat and mostly redundant to have both, and, having commons-lang alone I assume is more limited. I think most teams moving forward would be using commons-lang3 and it would be very nice if PDB was able to upgrade their dependency.

**Comment by diogoeag** [comment]
Case, you are welcome to contribute. Do you want to submit a pr?

**Comment by casewalker** [comment]
Ok Diogo, I created https://github.com/feedzai/pdb/pull/53.

As I comment in the PR, one of the changes from commons-lang 2.X to 3.X was losing StringEscapeUtils#escapeSql. I handled this by copying the function from 2.X into the PDB code. I am not sure that this is the best solution, it kind of smells, but it seemed like the cleanest thing for now. I am of course open to suggestions.

**Comment by dspereira004** [comment]
Well, currently I also think it's the cleanest solution for now. Also, thanks for the tests for the StringUtils class.

**Comment by dspereira004** [comment]
Closing this issue as #53 has been merged.
